# Generated by Django 6.0.3 on 2026-03-07 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_title', models.CharField(max_length=255)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('cnr_number', models.CharField(blank=True, max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal'), ('civil', 'Civil'), ('administrative', 'Administrative'), ('other', 'Other')], default='other', max_length=100)),
                ('act_name', models.CharField(blank=True, max_length=255)),
                ('primary_section', models.CharField(blank=True, max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disposed', 'Disposed'), ('dismissed', 'Dismissed'), ('allowed', 'Allowed'), ('stay_granted', 'Stay Granted'), ('withdrawn', 'Withdrawn'), ('settled', 'Settled')], default='pending', max_length=50)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=50)),
                ('limitation_end_date', models.DateField(blank=True, null=True)),
                ('court_level', models.CharField(blank=True, choices=[('district', 'District Court'), ('sessions', 'Sessions Court'), ('high_court', 'High Court'), ('supreme_court', 'Supreme Court'), ('tribunal', 'Tribunal')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_level', models.CharField(max_length=100)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('appeal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_of', to='api.case')),
                ('parent_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseCourtDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_name', models.CharField(max_length=255)),
                ('court_complex', models.CharField(blank=True, max_length=255)),
                ('judge_name', models.CharField(blank=True, max_length=255)),
                ('bench_type', models.CharField(blank=True, help_text='Single Bench / Division Bench', max_length=100)),
                ('courtroom_number', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_details', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('complainant', 'Complainant'), ('accused', 'Accused'), ('petitioner', 'Petitioner'), ('respondent', 'Respondent')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_parties', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.case')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.client'),
        ),
    ]
