# Generated by Django 6.0.3 on 2026-03-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='caseparty',
            name='advocate',
        ),
    ]
